<a href="https://colab.research.google.com/github/JulioRan09/Porgramacion-Predictiva/blob/main/S06_Actividad_02_ALGEBRALINEAL_276572.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Actividad calificada — Álgebra lineal con NumPy

**Programación para Analítica Descriptiva y Predictiva**
Maestría en Inteligencia Artificial y Analítica de Datos — UACJ

---

**Material de estudio previo:** `Material_Extra_Algebra_Lineal_NumPy.ipynb`. Revísalo antes de resolver esta actividad.

**Entrega:** individual, en este notebook de Google Colab (comparte el enlace con permiso de edición para el docente).
**Plazo:** 7 días naturales a partir de la publicación de esta actividad.
**Penalización por entrega tardía:** 5% por día, hasta 7 días; después de eso, la actividad no se recibe.
**Valor total:** 100 puntos.

### Herramientas permitidas

Esta actividad evalúa `np.linalg.norm()`, `np.dot()`/`@`, `np.linalg.det()`, `np.linalg.inv()`, `np.linalg.solve()`, y las operaciones de NumPy ya vistas en sesiones anteriores. No uses pandas ni scikit-learn.

### Cómo se evalúa

Cada ejercicio indica su valor en puntos. Se evalúa el resultado correcto **y** el uso de la función específica de `np.linalg` indicada en cada enunciado — calcular a mano una fórmula que NumPy ya resuelve (por ejemplo, programar la fórmula del determinante 2×2 en vez de usar `np.linalg.det()`) no obtiene el puntaje completo.

In [1]:
import numpy as np

## Parte 1 — Vectores: perfiles de producto

Una tienda en línea representa cada producto como un vector de 3 componentes: calificación de calidad, calificación de precio, y calificación de servicio (escala 1 a 5, donde 5 es mejor). Ejecuta la siguiente celda para cargar los tres productos — **no la modifiques**.

In [2]:
producto_A = np.array([4.5, 3.2, 5.0])
producto_B = np.array([4.0, 2.8, 4.7])
producto_C = np.array([1.0, 5.0, 1.2])

print(producto_A, producto_B, producto_C)

[4.5 3.2 5. ] [4.  2.8 4.7] [1.  5.  1.2]


---

### Ejercicio 1 — Norma de los vectores (10 pts)

Calcula la norma de `producto_A`, `producto_B` y `producto_C` usando `np.linalg.norm()`.

In [3]:
# Tu código aquí

norma_a = np.linalg.norm(producto_A)
norma_b = np.linalg.norm(producto_B)
norma_c = np.linalg.norm(producto_C)

print(norma_a, norma_b, norma_c)


7.449161026585477 6.777167549942971 5.238320341483518


---

### Ejercicio 2 — Producto punto y ángulo (15 pts)

1. Calcula el producto punto entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando `np.dot()` o `@`.
2. Calcula el ángulo (en grados) entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`.
3. Con base en los ángulos obtenidos, indica (en un comentario o celda de texto) cuál de los dos productos (`B` o `C`) es más similar a `producto_A`, y por qué el ángulo es el indicador correcto para esa comparación.

In [4]:
# Tu código aquí
prod_AB = np.dot(producto_A, producto_B)
prod_AC = (producto_A @ producto_C)

print(f"El producto punto de A*B es: {prod_AB}, y el producto punto de A*C es: {prod_AC}")

El producto punto de A*B es: 50.46, y el producto punto de A*C es: 26.5


In [5]:
cos_AB = prod_AB / (norma_a * norma_b)
cos_AC = prod_AC / (norma_a * norma_c)

rad_AB = np.arccos(cos_AB)
ang_AB = np.degrees(rad_AB)

rad_AC = np.arccos(cos_AC)
ang_AC = np.degrees(rad_AC)

print(f"El ángulo entre A y B es: {ang_AB}, y el ángulo entre A y C es: {ang_AC}")

El ángulo entre A y B es: 1.7745815839558179, y el ángulo entre A y C es: 47.22509268261831


Los véctores más similares son A y B, ya que su ángulo es más pequeño que el del producto de A y C.

Tomar el ángulo es una buena manera de saber si dos vectores son similares, ya que, para vectores con diferencias de ángulos pequeños, podemos afirmar que dichos vectores están sobre aproximadamente la misma recta en el espacio. Para este ejemplo además, como todos los vectores tienen aproximadamente la misma magnitud, el ángulo se vuelve aún más critico.

---

### Ejercicio 3 — Normalización (10 pts)

Normaliza los tres vectores (`producto_A`, `producto_B`, `producto_C`) para obtener sus vectores unitarios. Verifica, imprimiendo el resultado, que la norma de cada vector normalizado sea 1.

In [6]:
# Tu código aquí
A_normalizado = producto_A / norma_a
B_normalizado = producto_B / norma_b
C_normalizado = producto_C / norma_c

print(A_normalizado, B_normalizado, C_normalizado)
print(np.linalg.norm(A_normalizado), np.linalg.norm(B_normalizado), np.linalg.norm(C_normalizado))

[0.60409488 0.42957858 0.67121653] [0.59021707 0.41315195 0.69350506] [0.19090089 0.95450444 0.22908106]
1.0 1.0 1.0


## Parte 2 — Matrices: mezcla de insumos

Una fábrica de jugos combina dos insumos (concentrado de fruta y agua) en distintas proporciones para dos líneas de producto. La matriz `M` representa esas proporciones (filas = línea de producto, columnas = insumo), y `P` representa un ajuste de escala para una nueva presentación. Ejecuta la siguiente celda — **no la modifiques**.

In [7]:
M = np.array([[2, 1],
              [1, 3]])

P = np.array([[1.5, 0],
              [0, 2.0]])

print(M)
print(P)

[[2 1]
 [1 3]]
[[1.5 0. ]
 [0.  2. ]]


---

### Ejercicio 4 — Multiplicación matricial (15 pts)

1. Calcula `M * P` (elemento a elemento) y `M @ P` (multiplicación matricial). Los resultados son distintos — en un comentario o celda de texto, explica brevemente por qué.
2. Verifica que las formas sean compatibles: ¿cuál sería el resultado de `P @ M`? Calcúlalo y compáralo con `M @ P` — ¿da el mismo resultado?

In [8]:
# Tu código aquí
MP = M * P
MP2 = M @ P

print(MP)
print(MP2)

[[3. 0.]
 [0. 6.]]
[[3.  2. ]
 [1.5 6. ]]


Para el caso de * se multiplica elemento a elemento (mismas posiciones).
Para el caso de la multiplicación matricial, lo hace con las reglas del algebra, es decir, fila a columna.

---

### Ejercicio 5 — Determinante e inversa (15 pts)

1. Calcula el determinante de `M` con `np.linalg.det()`. Confirma que `M` sí tiene inversa (determinante distinto de 0).
2. Calcula la inversa de `M` con `np.linalg.inv()`.
3. Verifica tu resultado calculando `M @ M_inv` — debe dar (aproximadamente) la matriz identidad.

In [9]:
# Tu código aquí
detM = np.linalg.det(M)
print(f"El determinante de M es: {detM}, distinto de cero.")

invM = np.linalg.inv(M)
print(invM)

M_MI = M @ invM
print(f"{M_MI}, es aproximadamente la matriz identidad")

El determinante de M es: 5.000000000000001, distinto de cero.
[[ 0.6 -0.2]
 [-0.2  0.4]]
[[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]], es aproximadamente la matriz identidad


---

### Ejercicio 6 — Sistema de ecuaciones (15 pts)

La fábrica necesita producir un lote que requiere en total 180 unidades de la línea 1 y 300 unidades de la línea 2, según las proporciones de `M`. Esto se representa como el sistema $Mx = b$, con:

```python
b = np.array([180, 300])
```

1. Resuelve el sistema con `np.linalg.solve()` para encontrar cuántas unidades de cada insumo (`x`) se necesitan.
2. Verifica tu solución multiplicando `M @ x` y confirmando que el resultado coincide con `b`.

In [10]:
b = np.array([180, 300])

# Tu código aquí

x = np.linalg.solve(M, b)
print(f"el vector solución es X = {x}")

print(f"M*X es igual a -> {M @ x}, igual a b")


el vector solución es X = [48. 84.]
M*X es igual a -> [180. 300.], igual a b


---

### Ejercicio 7 — Síntesis: distancia y similitud (20 pts)

Retomando los tres productos de la Parte 1:

1. Calcula la **distancia euclidiana** entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando la norma de la diferencia entre los vectores (`np.linalg.norm(a - b)`).
2. Calcula la **similitud coseno** entre los mismos pares — es el cociente que ya calculaste en el Ejercicio 2 antes de aplicar `arccos()`: $\frac{a \cdot b}{\|a\| \|b\|}$.
3. Con base en ambas métricas (distancia y similitud coseno), concluye en una cadena de texto impresa cuál producto (`B` o `C`) es más parecido a `producto_A`, y si ambas métricas coinciden en la misma conclusión.

In [11]:
# Tu código aquí
dist_AB = np.linalg.norm(producto_A - producto_B)
dist_AC = np.linalg.norm(producto_A - producto_C)

print(f"La distancia entre A y B es: {dist_AB}, y la distancia entre A y C es: {dist_AC}")
print(f"El cos de AB es ={cos_AB}, y el cos de AC es = {cos_AC}")

La distancia entre A y B es: 0.7071067811865476, y la distancia entre A y C es: 5.470831746635972
El cos de AB es =0.9995203969214979, y el cos de AC es = 0.6791199021706347


La distancia entre A y B es mucho más cercana que la de A y C.

Por otro lado, el cos de AB es más grande que AC y esto pareciera indicar un error, pero sin embargo, como se trata de un Cos, que su valor esté cercano a 1 indica que el angulo es pequeño entre los vectores, el ángulo será cercano a 0° o 180°, esto ya se adelantaba desde el ejercicio 2.

---

## Antes de entregar

- Verifica que el notebook completo corra de principio a fin sin errores (**Entorno de ejecución → Ejecutar todas**).
- Confirma que no usaste pandas ni scikit-learn.
- Comparte el notebook con permiso de **edición** para el docente.